[build]
  command = "pnpm install --prod --ignore-scripts --ignore-workspace"
  functions = "netlify/functions"
  publish = "netlify/static"

[build.environment]
  NODE_VERSION = "20"

# Route all requests to the Waline comment function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/comment/:splat"
  status = 200
  force = true